baseurl = "/"
languageCode = "en-us"
theme = "friend"
paginate = 4
enableEmoji = true
googleAnalytics = "UA-133160807-4"

[params]
  contentTypeName = "posts"
  defaultTheme = "light"
  showMenuItems = 2
  showReadingTime = true

[languages]
  [languages.en]
    title = "Tech Aware"
    subtitle = "Technology Simplified! ❤️"
    keywords = "Security, Technology, Software, Internet"
    copyright = "Free and Open-Source ❤️ Tech Aware &copy 2021"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    lastModDisplay = "Modified: "

    [languages.en.params.logo]
      logoText = "Tech Aware"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/iamvkm/techaware"